language: r

cache: packages

before_install:
  - tlmgr install tcolorbox
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

warnings_are_errors: false

r_packages: 
  - RColorBrewer
  - pheatmap
